# Generated by Django 4.2.7 on 2025-11-10 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_courseannouncement_coursenote_discussion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='video_file',
            field=models.FileField(blank=True, help_text='Upload video file directly', null=True, upload_to='lesson_videos/'),
        ),
    ]
